import os
if not os.getenv('FLUENT_PROD_DIR'):
    import ansys.fluent.core as pyfluent
    flglobals = pyfluent.setup_for_fluent(product_version="25.2.0", mode="meshing", dimension=3, precision="double", processor_count=1, ui_mode="gui", graphics_driver="dx11", gpu=False)
    globals().update(flglobals)

workflow.TaskObject['Set Up Periodic Boundaries'].Arguments.set_state({r'AutoMultiplePeriodic': r'no',r'LCSOrigin': {r'OriginX': 0,r'OriginY': 0,r'OriginZ': 0,},r'LCSVector': {r'VectorX': 0,r'VectorY': 0,r'VectorZ': 0,},r'LabelList': [r'per1_near', r'per1_off', r'per2_near', r'per2_off'],r'ListAllLabelToggle': False,r'MeshObject': r'',r'Method': r'Automatic - pick both sides',r'MultipleOption': r'Paired',r'PeriodicityAngle': 36,r'RemeshBoundariesOption': r'auto',r'SelectionType': r'label',r'TransShift': {r'ShiftX': 0,r'ShiftY': 0,r'ShiftZ': 1,},r'Type': r'Rotational',})
workflow.TaskObject['Set Up Periodic Boundaries'].Arguments.set_state({r'AutoMultiplePeriodic': r'no',r'LCSOrigin': {r'OriginX': 0,r'OriginY': 0,r'OriginZ': 0,},r'LCSVector': {r'VectorX': 0,r'VectorY': 0,r'VectorZ': 1,},r'LabelList': [r'per1_near'],r'ListAllLabelToggle': False,r'MeshObject': r'',r'Method': r'Manual - pick reference side',r'MultipleOption': r'Paired',r'PeriodicityAngle': 36,r'RemeshBoundariesOption': r'yes',r'SelectionType': r'label',r'TransShift': {r'ShiftX': 0,r'ShiftY': 0,r'ShiftZ': 1,},r'Type': r'Rotational',})
workflow.TaskObject['Set Up Periodic Boundaries'].Revert()
workflow.TaskObject['Set Up Periodic Boundaries'].Arguments.set_state({r'AutoMultiplePeriodic': r'no',r'LCSOrigin': {r'OriginX': 0,r'OriginY': 0,r'OriginZ': 0,},r'LCSVector': {r'VectorX': 0,r'VectorY': 0,r'VectorZ': 1,},r'LabelList': [r'per1_off'],r'ListAllLabelToggle': False,r'MeshObject': r'',r'Method': r'Manual - pick reference side',r'MultipleOption': r'Paired',r'PeriodicityAngle': 36,r'RemeshBoundariesOption': r'yes',r'SelectionType': r'label',r'TransShift': {r'ShiftX': 0,r'ShiftY': 0,r'ShiftZ': 1,},r'Type': r'Rotational',})
workflow.TaskObject['Set Up Periodic Boundaries'].Revert()
workflow.TaskObject['Set Up Periodic Boundaries'].Arguments.set_state({r'AutoMultiplePeriodic': r'no',r'LCSOrigin': {r'OriginX': 0,r'OriginY': 0,r'OriginZ': 0,},r'LCSVector': {r'VectorX': 0,r'VectorY': 0,r'VectorZ': 1,},r'LabelList': [r'per1_off'],r'ListAllLabelToggle': False,r'MeshObject': r'',r'Method': r'Manual - pick reference side',r'MultipleOption': r'Paired',r'PeriodicityAngle': 60,r'RemeshBoundariesOption': r'yes',r'SelectionType': r'label',r'TransShift': {r'ShiftX': 0,r'ShiftY': 0,r'ShiftZ': 1,},r'Type': r'Rotational',})
workflow.TaskObject['Set Up Periodic Boundaries'].Revert()
workflow.TaskObject['Set Up Periodic Boundaries'].Arguments.set_state({r'AutoMultiplePeriodic': r'no',r'LCSOrigin': {r'OriginX': 0,r'OriginY': 0,r'OriginZ': 0,},r'LCSVector': {r'VectorX': 0,r'VectorY': 0,r'VectorZ': 1,},r'LabelList': [r'per1_off'],r'ListAllLabelToggle': False,r'MeshObject': r'',r'Method': r'Manual - pick reference side',r'MultipleOption': r'Paired',r'PeriodicityAngle': -60,r'RemeshBoundariesOption': r'yes',r'SelectionType': r'label',r'TransShift': {r'ShiftX': 0,r'ShiftY': 0,r'ShiftZ': 1,},r'Type': r'Rotational',})
workflow.TaskObject['Set Up Periodic Boundaries'].Revert()
workflow.TaskObject['Set Up Periodic Boundaries'].Arguments.set_state({r'AutoMultiplePeriodic': r'no',r'LCSOrigin': {r'OriginX': 0,r'OriginY': 0,r'OriginZ': 0,},r'LCSVector': {r'VectorX': 0,r'VectorY': 0,r'VectorZ': 1,},r'LabelList': [r'per1_near', r'per2_near'],r'ListAllLabelToggle': False,r'MeshObject': r'',r'Method': r'Automatic - pick both sides',r'MultipleOption': r'Paired',r'PeriodicityAngle': -60,r'RemeshBoundariesOption': r'yes',r'SelectionType': r'label',r'TransShift': {r'ShiftX': 0,r'ShiftY': 0,r'ShiftZ': 1,},r'Type': r'Rotational',})
workflow.TaskObject['Set Up Periodic Boundaries'].Revert()
workflow.TaskObject['Set Up Periodic Boundaries'].Execute()
workflow.TaskObject['Set Up Periodic Boundaries'].InsertNextTask(CommandName=r'SetUpPeriodicBoundaries')
workflow.TaskObject['Set Up Periodic Boundaries 1'].Arguments.set_state({r'AutoMultiplePeriodic': r'no',r'LCSOrigin': {r'OriginX': -2.201853362748807e-06,r'OriginY': -8.297532616552417e-08,r'OriginZ': -5.173715795361968,},r'LCSVector': {r'VectorX': 3.273346001455631e-09,r'VectorY': 1.690291983841371e-09,r'VectorZ': -1,},r'LabelList': [r'per1_off', r'per2_off'],r'ListAllLabelToggle': False,r'MeshObject': r'',r'Method': r'Automatic - pick both sides',r'MultipleOption': r'Paired',r'PeriodicityAngle': 36.00000002803291,r'RemeshBoundariesOption': r'auto',r'SelectionType': r'label',r'TransShift': {r'ShiftX': 0,r'ShiftY': 0,r'ShiftZ': 1,},r'Type': r'Rotational',})
workflow.TaskObject['Set Up Periodic Boundaries 1'].Execute()
meshing.exit()
